#!/usr/bin/env python

import gentk

client = gentk.client.client("http://127.0.0.1", "8000")
client.project = "test.00"

print(client.get_structure(0))
print(client.get_genes())
print(client.get_genes_for_segment(0, 2))
