#!/usr/bin/env python

import sqlite3
import re
import sys
import os


#
# handle command line arguments
#
project = ""
bID = 300
if (len(sys.argv) < 2):
    print("ERROR: must include path to project directory")
    exit(0)
else:
    project = sys.argv[1]
    if (len(sys.argv) > 2):
        bID = sys.argv[2]

#
# create the database connection
#
db = os.path.join(project, 'generated/generated-project.db')
print("Testing database: {}".format(db))
conn = sqlite3.connect(db)
c = conn.cursor()

#
# get genes
#
if False:
    c.execute('''SELECT * from segments where ID == ? ''', (bID,))
    results = c.fetchone()
    start = results[0]
    end   = results[1] 
    c.execute('''SELECT gene_name from genes WHERE start >= ? AND end < ? ORDER BY gene_name''', (start, end))
    genes = []
    for g in c.fetchall():
        genes.append(g[0])


    if (len(genes) != 0):
        print("genes: {}".format(', '.join(genes)))


#
# close
#
conn.close()
