#!/usr/bin/env python

import gentk

# test.00
if True:
    client = gentk.client.client("http://127.0.0.1", "8000")
    client.project = "test.00"

    print(client.get_structure(0))

# test.01
if False:
    client = gentk.client.client("http://127.0.0.1", "8001")
    client.project = "test.01"

    print(client.get_structure(0))
    print(client.get_genes())

    print(client.get_genes_for_segment(0, 100))
    print(client.get_segments_for_gene(0, "Gm5384"))

    print(client.get_genes_for_segment(0, 800))
    print(client.get_segments_for_gene(0, "Sh3kbp1"))
    print(client.get_segments_for_gene(0, "Map3k15"))
