#!/usr/bin/env python

import sqlite3
import re
import sys
import os
import bbi


#
# handle command line arguments
#
project = ""
bID = 300
if (len(sys.argv) < 2):
    print("ERROR: must include path to project directory")
    exit(0)
else:
    project = sys.argv[1]
    if (len(sys.argv) > 2):
        bID = sys.argv[2]

#
# create the database connection
#
db = os.path.join(project, 'generated/generated-project.db')
bbifile = os.path.join(project, 'source/0/GSM2862886_ChIP_MEF_WT_H3K27me3_cas_Rep1.bw')
# GSM2862886_ChIP_MEF_WT_H3K27me3_mus_Rep1.bw
print("Testing database: {}".format(db))
conn = sqlite3.connect(db)
c = conn.cursor()

#
# get genes
#
c.execute('''SELECT start, end from segments where ID == ? ''', (bID,))
results = c.fetchone()
c.execute('''SELECT gene_name, start, end from genes ORDER BY gene_name''')
num_genes = 0
for g in c.fetchall():
    num_genes = num_genes + 1
    print("Gene: {}".format(g))

    data = bbi.fetch(bbifile, "chrX", int(g[1]), int(g[2]), 100 )

print("Num genes: {}".format(num_genes))

#
# close
#
conn.close()
